app.repository.type=database

# Production Database (PostgreSQL)
db.url=jdbc:postgresql://ep-royal-pond-adar8bsz-pooler.c-2.us-east-1.aws.neon.tech/QuantityMeasurement
db.username=neondb_owner
db.password=npg_JVdmz0AI1xRU
db.driverClassName=org.postgresql.Driver
db.pool.maxSize=10
db.pool.minIdle=2
db.pool.connectionTimeoutMs=30000
db.pool.idleTimeoutMs=600000
db.pool.maxLifetimeMs=1800000

# Test Database (H2)
test.db.url=jdbc:h2:mem:quantity_measurement_test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
test.db.username=sa
test.db.password=
test.db.driverClassName=org.h2.Driver

logging.level=INFO