server:
  port: 8084

spring:
  application:
    name: payment-service
  datasource:
    url: ${PAYMENT_DATASOURCE_URL:}
    driver-class-name: ${PAYMENT_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    username: ${PAYMENT_DATASOURCE_USERNAME:neondb_owner}
    password: ${PAYMENT_DATASOURCE_PASSWORD:}
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

razorpay:
  key-id: ${RAZORPAY_KEY_ID:}
  key-secret: ${RAZORPAY_KEY_SECRET:}

app:
  credits:
    per-recharge-unit: 5
    price-per-unit-paise: 100
